data/settings.json, docs/getting-started.md
* Adds draft for the program on the sidebar
=> Adds draft for the whole program

data/settings.json
* Translates syllabus to english
=> Translates syllabus to english

docs/arrays.md
=> Adds array lesson

docs/hashes.md
=> Adds hash lesson

data/settings.json, docs/hashes.md
* Adds a bit more information to create a hash
=> Adds a bit more information to create a hash

docs/introduction-to-each.md
=> Adds each lesson

docs/methods.md
* Adds block and default arguments to methods lesson
=> Adds block and default arguments

data/settings.json, docs/introduction-to-enumerable.md
=> Adds enumerables lesson

data/settings.json, docs/install-ruby.md
* install ruby  in Ubuntu, Mac, wsl2 windows 
* Setup vscode
=> Add Module 0

docs/nested-collections.md
* Adds the nested collection lesson
=> Adds the nested collection lesson

docs/classes-and-instances.md
=> Adds the classes lesson

docs/variables-scope.md
=> Adds variable scope lesson

data/settings.json, docs/inheritance.md, src/assets/scss/globals.scss
=> Adds inheritance lesson

docs/mocks-and-stubs.md, src/assets/scss/globals.scss
=> Adds mocks and stubs lesson

docs/data-types.md, docs/install-ruby.md, docs/methods.md, docs/setup-vscode.md
With all the possible humbleness, this is just a small proposal as we were aimed to do at the meetings. It is really great content the one I'm reading so I would feel honored with being able to contribute at least with a grain of sand.
I was skimming among the whole content and just pointed out a few typos or extra spaces appearing, aside from some text-content switching but the whole thing just in regards to a better UX.
* The check was made with tools like **grammarly**,  **hemmingway** and **interest in your work**
* The following documents (`.md`) were changed:
- `docs/install-ruby.md`
- `docs/setup-vscode.md`
- `docs/data-types.md`
- `docs/methods.md`
<h4>I'll be more than glad to receive any feedback on the proposal so I can contribute in much better ways to your project (which is …
=> Small text content check proposal

docs/debugging.md
* Finishes the debugging lesson
=> Finishes the debugging lesson

data/settings.json, docs/web-and-http.md
* Renames the web and http lesson
=> Renames the web and http lesson

data/settings.json, docs/introduction-to-mvc.md, docs/introduction-to-rails.md, docs/static-pages.md
* Adds introduction to rails lesson
=> Adds introduction to rails lesson

docs/introduction-to-helpers.md, docs/static-pages.md
* Adds introduction to helpers lesson
=> Adds introduction to helpers lesson

docs/modeling-users.md
* Adds the modeling users lesson
=> Adds the modeling users lesson
